### ISSUE TITLE
Inquiry on Reproducing Substructure Analysis Results from Paper

### ISSUE THREAD

**Issue by ZERONE182** [felixjwong/antibioticsai#1]
Dear,
I hope this message finds you well. First, I want to express my admiration for the impressive work you've done—your project has truly been insightful and valuable. I am currently engaging with your substructure analysis, attempting to replicate the results depicted in Fig. 3(d) of your paper. However, I've encountered some variability in the results across different runs, which seem to lack the consistent grouping shown in the paper.

Here are the varied results from my four attempts:

<img width="377" alt="image" src="https://github.com/felixjwong/antibioticsai/assets/76674775/afd9da7e-8ed3-46ff-9c37-e52473094532">
<img width="377" alt="image" src="https://github.com/felixjwong/antibioticsai/assets/76674775/e77dcdac-5c8f-4d43-ae21-2c40988ffd9e">
<img width="377" alt="image" src="https://github.com/felixjwong/antibioticsai/assets/76674775/5c7ee2db-aef0-456d-bb85-d7906cf6d5f3">
<img width="377" alt="image" src="https://github.com/felixjwong/antibioticsai/assets/76674775/3dfc1dde-10eb-4fc8-a01b-b920b08c3128">

Could you please share any specific methods or adjustments you employed to achieve the stable groupings as illustrated? Any guidance or additional insights would be greatly appreciated to help me better understand the process.

Thank you very much for your time and assistance.

Warm regards,

**Comment by felixjwong** [comment]
Hi Yan, thanks for your note. The grouping is inherently a stochastic process, as detailed in the paper. The consistency of the substructures that are outputted will depend on the underlying distributions of substructures in the compounds, such that more common substructures are more likely to be identified through the process of comparing two molecules with RDKit's FindMCS function. 

That said, there are ways to improve consistency, which include the following:

1. The process may be run N times and only the substructures with the largest numbers of associated molecules can be shortlisted (and confirmed to have non-overlapping molecules). 
2. It may be helpful to identify substructures shared across different runs of the procedure, as these substructures are likely more enriched in the underlying molecule set. 
3. Changing the parameters of the procedure (e.g. number of min and max atoms) may allow it to produce more relevant results for a dataset of interest. 
4. Running the procedure on a larger set of molecules can oftentimes be helpful as shared substructures may be more likely to be enriched.

Let me know if this helps.
