### ISSUE TITLE
Why the rationale scaffold set into 5?

### ISSUE THREAD

**Issue by BIOBRICK** [felixjwong/antibioticsai#4]
Hi:

Very impressive work. I'm taking a closer look at your genius work and having a problem unable to find answer in your paper or quote in code.

I notice in notebooks/Filtering hits and computing rationale scaffolds.ipynb, the part "Sample scaffolds shared between rationales", there is a hyper para **NUM_GROUPS** was set into 5.

1. Is there any reason for this number?
2. Can I try other number? If I have more mols, like 1000 hits, can I set **NUM_GROUPS**  into 10 or more?

Many thks for your reply!

**Comment by felixjwong** [comment]
Hi, the value of NUM_GROUPS is arbitrary, but should be selected in a way that makes sense for considering rationale scaffolds based on the chemical structures and diversity of the hits. I would suggest experimenting with this value to see what makes the most sense for your dataset and models.

**Comment by BIOBRICK** [comment]
> Hi, the value of NUM_GROUPS is arbitrary, but should be selected in a way that makes sense for considering rationale scaffolds based on the chemical structures and diversity of the hits. I would suggest experimenting with this value to see what makes the most sense for your dataset and models.

Thanks a lot! I just want to know how this number comes from and I now get it. I 'll try different number in my dataset to acquire the most meaningful result~
